### ISSUE TITLE
scrollable popover

### ISSUE THREAD

**Issue by ErfanTech** [sudospaes/x-ui#52]
I am currently working on making the popover scrollable when its height exceeds a certain limit. After inspecting the HTML structure, I found that the relevant CSS class, `.ant-popover-inner-content`, is not present or accessible in the existing stylesheets.

**Proposed Solution:**

To address this, I suggest adding the following CSS style to make the popover scrollable when its height is too long:

```css
.ant-popover-inner-content {
    max-height: 400px;
    overflow-y: auto;
}
```

**Additional Information:**

I couldn't locate the `.ant-popover-inner-content` class in the existing stylesheets. Could you please guide me to the correct file or suggest an alternative approach?

Thanks for your assistance!
